overrides:
  js-yaml@>=4.0.0 <4.3.0: 4.3.1
  brace-expansion@>=1.0.0 <1.1.18: 1.1.18
  brace-expansion@>=5.0.0 <5.0.9: 5.0.9
  fast-uri@>=3.0.0 <3.1.5: 3.1.5
  '@xmldom/xmldom@>=0.7.0 <0.8.14': 0.8.14

allowBuilds:
  esbuild: true
  msw: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
